// Client-side export utilities: Transcript (.txt) and Report (.docx).
// Real file downloads (no server round-trip) so they work on Vercel as static.
//
// PDF + print for BOTH transcript and report live in ONE shared service (./pdf) so
// the download is the same document as the print preview and multilingual text stays
// readable. Re-exported here so existing call sites keep importing from ./download.
export { downloadReportPdf, downloadTranscriptPdf, printReport, printTranscript } from './pdf.js';

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
} from 'docx';
import { saveAs } from 'file-saver';
import {
  ReportData,
  MedicationRow,
  ComplaintRow,
  AllergyRow,
  SystemGroup,
  Vitals,
  FollowUp,
} from '../types';
import {
  REPORT_SECTIONS,
  ColumnDef,
  sectionHasContent,
  COMPLAINT_COLUMNS,
  ALLERGY_COLUMNS,
  TREATMENT_COLUMNS,
  VITALS_FIELDS,
  FOLLOWUP_FIELDS,
} from './report';

const cellText = (row: Record<string, any>, col: ColumnDef): string => {
  const v = row[col.key];
  if (typeof v === 'string' && v) return v;
  // Legacy medication rows stored `dosage` instead of `dose`.
  if (col.key === 'dose' && typeof row.dosage === 'string') return row.dosage;
  return '';
};

export interface ExportMeta {
  patientName?: string;
  date?: string;
}

// Make a safe, readable file name like "report_jane-doe_2026-06-17".
function fileName(kind: string, meta: ExportMeta, ext: string): string {
  const name = (meta.patientName || 'patient')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
  const date = (meta.date || '').replace(/[^0-9a-zA-Z]+/g, '-').replace(/(^-|-$)/g, '');
  return [kind, name, date].filter(Boolean).join('_') + '.' + ext;
}

// ── Transcript: TXT ──────────────────────────────────────────
export function downloadTranscriptTxt(text: string, meta: ExportMeta): void {
  const header = [
    'MediScribe AI — Consultation Transcript',
    meta.patientName ? `Patient: ${meta.patientName}` : '',
    meta.date ? `Date: ${meta.date}` : '',
    '',
    '',
  ].filter((l, i) => l !== '' || i >= 3);
  const blob = new Blob([header.join('\n') + (text || '')], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, fileName('transcript', meta, 'txt'));
}

// Non-empty key/value pairs for the vitals + follow-up sections.
const vitalsPairs = (v: Vitals): [string, string][] =>
  VITALS_FIELDS.filter(f => (v[f.key] || '').trim()).map(f => [f.label, v[f.key]]);

const followUpPairs = (f: FollowUp): [string, string][] =>
  FOLLOWUP_FIELDS.filter(x => (f[x.key] || '').trim()).map(x => [x.label, f[x.key]]);


// ── Report: DOCX (Premium Clinical Report — empty sections omitted) ──
export async function downloadReportDocx(report: ReportData, meta: ExportMeta): Promise<void> {
  const children: (Paragraph | Table)[] = [];

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: 'MEDISCRIBE AI', bold: true, color: '1D4ED8', size: 20 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: 'CLINICAL REPORT', bold: true, size: 34 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
      children: [
        new TextRun({
          text: [meta.patientName, meta.date].filter(Boolean).join('  •  ') || 'Generated by MediScribe AI',
          color: '64748B',
          size: 20,
        }),
      ],
    }),
  );

  const heading = (text: string) =>
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 220, after: 80 },
      children: [new TextRun({ text, bold: true, color: '1D4ED8', size: 24 })],
    });

  const buildTable = (cols: ColumnDef[], rows: Record<string, any>[]) => {
    const headerRow = new TableRow({
      tableHeader: true,
      children: cols.map(
        c =>
          new TableCell({
            shading: { fill: 'EFF6FF' },
            children: [new Paragraph({ children: [new TextRun({ text: c.label, bold: true, size: 16 })] })],
          }),
      ),
    });
    const bodyRows = rows.map(
      r =>
        new TableRow({
          children: cols.map(
            c =>
              new TableCell({
                children: [new Paragraph({ children: [new TextRun({ text: cellText(r, c), size: 16 })] })],
              }),
          ),
        }),
    );
    return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [headerRow, ...bodyRows] });
  };

  const kvTable = (pairs: [string, string][]) => {
    const rows = pairs.map(
      ([k, v]) =>
        new TableRow({
          children: [
            new TableCell({
              shading: { fill: 'F8FAFC' },
              width: { size: 35, type: WidthType.PERCENTAGE },
              children: [new Paragraph({ children: [new TextRun({ text: k, bold: true, size: 16 })] })],
            }),
            new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: v, size: 16 })] })] }),
          ],
        }),
    );
    return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows });
  };

  let n = 0;
  for (const section of REPORT_SECTIONS.filter(s => sectionHasContent(report, s))) {
    n += 1;
    children.push(heading(`${n}. ${section.title}`));
    const value = report[section.key];

    switch (section.kind) {
      case 'overview':
        children.push(new Paragraph({ children: [new TextRun({ text: (value as string).trim() })] }));
        break;
      case 'complaints':
        children.push(buildTable(COMPLAINT_COLUMNS, value as ComplaintRow[]));
        break;
      case 'allergies':
        children.push(buildTable(ALLERGY_COLUMNS, value as AllergyRow[]));
        break;
      case 'medications':
        children.push(buildTable(section.columns || TREATMENT_COLUMNS, value as MedicationRow[]));
        break;
      case 'vitals':
        children.push(kvTable(vitalsPairs(value as Vitals)));
        break;
      case 'followup':
        children.push(kvTable(followUpPairs(value as FollowUp)));
        break;
      case 'groups':
        for (const g of (value as SystemGroup[]).filter(x => x.findings.length || x.name.trim())) {
          children.push(
            new Paragraph({
              spacing: { before: 60, after: 20 },
              children: [new TextRun({ text: g.name || 'Findings', bold: true, color: '334155', size: 20 })],
            }),
          );
          for (const f of g.findings.filter(Boolean)) {
            children.push(new Paragraph({ text: f, bullet: { level: 0 } }));
          }
        }
        break;
      default: // bullets
        for (const item of (value as string[]).filter(Boolean)) {
          children.push(new Paragraph({ text: item, bullet: { level: 0 } }));
        }
        break;
    }
  }

  // Signature block
  children.push(
    new Paragraph({
      alignment: AlignmentType.RIGHT,
      spacing: { before: 600 },
      children: [new TextRun({ text: '__________________________', color: '334155' })],
    }),
    new Paragraph({
      alignment: AlignmentType.RIGHT,
      children: [new TextRun({ text: "Doctor's Signature", bold: true, size: 18 })],
    }),
  );

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  saveAs(blob, fileName('report', meta, 'docx'));
}
