-- AlterTable
ALTER TABLE "Patient" ADD COLUMN "age" INTEGER;
ALTER TABLE "Patient" ADD COLUMN "gender" TEXT;
ALTER TABLE "Patient" ADD COLUMN "healthConcern" TEXT;
ALTER TABLE "Patient" ADD COLUMN "source" TEXT NOT NULL DEFAULT 'staff';
ALTER TABLE "Patient" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
